version: "3"
services:
    postgres: 
        image: clkao/postgres-plv8:9.6-2.0
        environment:
            - postgres/variables.env
        ports:
            - "5432:5432"

    
    mssql:
        image: "microsoft/mssql-server-linux"
        env_file:
            - mssql/variables.env
        ports:
          - "1433:1433"